# Generated by Django 4.1.2 on 2022-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_price',
            field=models.FloatField(default=0.0),
        ),
    ]
