# Generated by Django 4.1.4 on 2022-12-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_name_en_category_name_uk_producer_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='first_price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='first_price_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_uk',
        ),
    ]
