# Generated by Django 4.1.4 on 2023-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_qty_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price_in_cart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
